apiVersion: v1
kind: Secret
metadata:
  name: argus-jupyter-${WORKSPACE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: jupyterlab
    app.kubernetes.io/instance: "${WORKSPACE_NAME}"
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
type: Opaque
stringData:
  aws-access-key: "${S3_ACCESS_KEY}"
  aws-secret-key: "${S3_SECRET_KEY}"
