"""SQLAlchemy ORM model for dataset embeddings (pgvector).

Stores vector embeddings generated by the active embedding provider.
Each dataset has at most one embedding row (1:1 relationship).
"""

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text, func

from app.core.database import Base

try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    # pgvector not installed — define a placeholder so the module can still be imported.
    # The table will not be created, and embedding operations will fail gracefully.
    Vector = None


class DatasetEmbedding(Base):
    """Vector embedding for semantic search on catalog datasets."""

    __tablename__ = "catalog_dataset_embeddings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    dataset_id = Column(
        Integer,
        ForeignKey("catalog_datasets.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    # pgvector column — dimension set at table creation time
    embedding = Column(Vector(384) if Vector else Text, nullable=False)
    # The concatenated text that was embedded (for staleness detection)
    source_text = Column(Text, nullable=False)
    # Provenance tracking
    model_name = Column(String(200), nullable=False)
    provider = Column(String(50), nullable=False)
    dimension = Column(Integer, nullable=False, default=384)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
