apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-keycloak-db-data
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
