apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-powerdns-mysql-data
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: powerdns
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
