apiVersion: v1
kind: Secret
metadata:
  name: powerdns-secrets
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: powerdns
    app.kubernetes.io/part-of: argus-insight
type: Opaque
stringData:
  # Change these values before deploying to production
  mysql_root_password: "Argus!nsight2026"
  mysql_user: "pdns"
  mysql_password: "pdns"
  pdns_api_key: "Argus!nsight2026"
