apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-zot-data
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: zot-registry
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
